workflows:
  android-build:
    name: Android Build with Tests
    max_build_duration: 60 # in minutes
    instance_type: mac_mini_m1 # or mac_mini (or another valid option)
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        ANDROID_HOME: /opt/android-sdk
   
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter doctor
          flutter doctor --android-licenses
              
      - name: Run Integration Tests 
        script: |
          flutter devices  # List available devices 
          flutter drive --target=test_driver/e2e.dart -d all  # Replace with the correct device ID

      - name: Build the APK
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      scripts:
        - name: Upload APK to a server (optional)
          script: |
            curl -F "file=@build/app/outputs/flutter-apk/app-release.apk" https://your-upload-server.com/upload
